Repository redhat-beyond/ResuMe, pull requests merged in 2022-04, with the labels that each got.

#50 Adding Resume model
  posts/admin.py
  posts/migrations/0002_resume.py
  posts/models.py
  posts/tests.py
Labels: Status/In-Progress

#62 Adding Users and Profiles test data
  media/profile_pics/alon.jpg
  media/profile_pics/matan.jpg
  media/profile_pics/omer.jpg
  media/profile_pics/tomer.jpeg
  media/profile_pics/yuli.jpg
  users/migrations/0002_add_users_test.py
Labels: Status/In-Progress

#64 Adding idea files to gitignore
  .gitignore
Labels: ready to merge

#65 Updating documantation files
  docs/ResuMe DFD diagram - Full DFD.jpeg
  docs/ResuMe ER diagram - Full ERD.jpeg
  docs/ResuMe ERD.jpeg
Labels: documentation

#56 Added the Rating model
  posts/admin.py
  posts/migrations/0003_rating.py
  posts/models.py
  posts/tests.py
Labels: ready to merge

#42 Adding the direct_message model
  direct_message/admin.py
  direct_message/migrations/0001_initial.py
  direct_message/models.py
  direct_message/tests.py
Labels: ready for review

#81 Updating ERD for profession
  docs/ResuMe ER diagram - Full ERD.jpeg
  docs/ResuMe ER diagram-Full ERD.jpeg
Labels: documentation

#79 Add profession to users model
  users/migrations/0002_profile_profession.py
  users/migrations/0003_add_users_test.py
  users/models.py
  users/tests.py
Labels: ready to merge

#67 Adding Comment model
  posts/admin.py
  posts/migrations/0004_comment.py
  posts/models.py
  posts/test_comment.py
Labels: ready to merge

#49 Adding Poll model
  posts/admin.py
  posts/migrations/0005_poll.py
  posts/models.py
  posts/tests.py
Labels: ready for review

#72 Adding URLs and blank templates for all apps
  ResuMe/urls.py
  direct_message/templates/direct_message/home.html
  direct_message/urls.py
  direct_message/views.py
  posts/templates/posts/about.html
  posts/templates/posts/feed.html
  posts/templates/posts/search.html
  posts/urls.py
  posts/views.py
  users/templates/users/login.html
  users/templates/users/logout.html
  users/templates/users/profile.html
  users/urls.py
  users/views.py
Labels: ready to merge

#87 Adding profile profession test data
  users/migrations/0003_add_users_test.py
Labels: ready to merge

#77 Adding Base template and about template
  ResuMe/settings.py
  direct_message/templates/direct_message/home.html
  posts/static/posts/about.css
  posts/templates/posts/about.html
  posts/templates/posts/feed.html
  posts/templates/posts/search.html
  static/styles/index.css
  static/styles/main.css
  templates/base.html
  users/templates/users/login.html
  users/templates/users/logout.html
  users/templates/users/profile.html
Labels: ready to merge

#89 Displaying Posts on feed
  ResuMe/settings.py
  posts/static/posts/about.css
  posts/static/posts/feed.css
  posts/templates/posts/feed.html
  posts/tests/test_comment.py
  posts/tests/test_posts_views.py
  posts/tests/tests.py
  posts/urls.py
  posts/views.py
  static/styles/main.css
  tests/test_helloworld.py
Labels: ready to merge

#92 Create profile page and edit_profile page
  Pipfile
  Pipfile.lock
  ResuMe/settings.py
  users/forms.py
  users/models.py
  users/templates/users/edit-profile.html
  users/templates/users/profile.html
  users/test_views.py
  users/urls.py
  users/views.py
Labels: ready to merge

#52 Adding PollFile model
  posts/admin.py
  posts/migrations/0006_pollfile.py
  posts/models.py
  posts/tests/tests.py
Labels: ready to merge

#94 Adding Post detail view
  posts/templates/posts/post_detail.html
  posts/tests/conftest.py
  posts/tests/test_posts.py
  posts/tests/test_posts_views.py
  posts/urls.py
  posts/views.py
Labels: ready to merge

#103 Adding post resume test data
  media/files/1da9800c-da30-450f-8c8f-b84e48a0685d.png
  media/files/Alon Shakaroff.pdf
  media/files/Alon_Shakaroffs_resume.pdf
  media/files/Matan _CV.pdf
  media/files/Software Engineer.pdf
  media/files/Tomer Newman.pdf
  media/files/Yuli_CV.pdf
  media/files/admin.pdf
  media/files/lt44864860_quantized.png
  media/profile_pics/12646666_1697244330520241_4905516181965590805_o_Poxt4cQ.png
  media/profile_pics/444_NCcSNzs.png
  media/profile_pics/admin.jpg
  posts/migrations/0007_add_resume_test_data.py
  posts/migrations/0008_add_comment_test_data.py
  posts/migrations/0009_add_rating_test_data.py
  users/migrations/0003_add_users_test.py
Labels: ready to merge

#84 Setup login
  ResuMe/settings.py
  ResuMe/urls.py
  direct_message/views.py
  posts/views.py
  templates/base.html
  users/templates/users/login.html
  users/test_users_views.py
  users/test_views.py
  users/urls.py
Labels: ready to merge

#109 Making profile pictures smaller
  media/profile-icon.png
  media/profile_pics/alon.jpg
  media/profile_pics/matan.jpg
  media/profile_pics/omer.jpg
  media/profile_pics/tomer.jpeg
  media/profile_pics/yuli.jpg
Labels: ready to merge

#111 Add team picture
  README.md
  static/images/ResuMeTeam.png
Labels: ready to merge

#96 Adding create Resume view
  posts/models.py
  posts/static/posts/forms.css
  posts/templates/posts/feed.html
  posts/templates/posts/post_detail.html
  posts/templates/posts/resume_form.html
  posts/tests/conftest.py
  posts/tests/test_posts.py
  posts/tests/test_posts_views.py
  posts/urls.py
  posts/views.py
  static/styles/main.css
  templates/base.html
Labels: ready to merge
