Repository redhat-beyond/ResuMe, pull requests merged in 2022-05, with the labels that each got.

#119 Add profile tests
  tests/conftest.py
  tests/direct_message_tests/tests.py
  tests/posts_tests/test_comment.py
  tests/posts_tests/test_posts.py
  tests/posts_tests/test_posts_views.py
  tests/users_tests/test_user_model.py
  tests/users_tests/test_users_views.py
  users/test_users_views.py
  users/tests.py
Labels: ready to merge

#98 Adding update a Resume View
  posts/urls.py
  posts/views.py
  tests/posts_tests/test_posts_views.py
Labels: ready to merge

#102 Adding comments view
  posts/models.py
  posts/static/posts/feed.css
  posts/templates/posts/comment_form.html
  posts/templates/posts/feed.html
  posts/templates/posts/post_detail.html
  posts/urls.py
  posts/views.py
  static/styles/main.css
  tests/conftest.py
  tests/posts_tests/test_posts_views.py
Labels: ready to merge

#126 Delete direct-message from UI
  ResuMe/urls.py
  direct_message/urls.py
  templates/base.html
  tests/users_tests/test_users_views.py
Labels: ready to merge

#135 Changing user's password
  users/migrations/0003_add_users_test.py
Labels: ready for review

#133 Rating view
  posts/models.py
  posts/static/posts/rating.css
  posts/templates/posts/feed.html
  posts/templates/posts/post_detail.html
  posts/templates/posts/rating_form.html
  posts/templates/posts/rating_view.html
  posts/urls.py
  posts/views.py
  tests/conftest.py
  tests/posts_tests/test_posts.py
  tests/posts_tests/test_ratings.py
Labels: ready to merge

#125 Fixing posts tests
  tests/posts_tests/test_posts_views.py
Labels: ready to merge

#138 Adding direct_message views
  ResuMe/urls.py
  direct_message/static/direct_message/forms.css
  direct_message/static/direct_message/message.css
  direct_message/templates/direct_message/direct_message.html
  direct_message/templates/direct_message/home.html
  direct_message/templates/direct_message/main_messages.html
  direct_message/templates/direct_message/message_form.html
  direct_message/urls.py
  direct_message/views.py
  templates/base.html
  tests/conftest.py
  tests/direct_message_tests/test_view.py
Labels: ready to merge

#128 Add profile view option
  ResuMe/urls.py
  posts/templates/posts/feed.html
  posts/templates/posts/post_detail.html
  tests/users_tests/test_users_views.py
  users/templates/users/profile_details.html
  users/views.py
Labels: ready to merge

#140 Fixed minor UI bugs
  posts/static/posts/feed.css
  users/templates/users/profile.html
  users/templates/users/profile_details.html
Labels: Status/New, ready for review
